### PR TITLE
Fixed spelling error

### PR DESCRIPTION
**Pull request by TheDoctorSoda**

### CODE REVIEW

**Comment by TheDoctorSoda** [comment]
Actually I'll just let you do this. You'll have to edit it in multiple places :P

**Comment by modmuss50** [comment]
I may wait till 1.9 to do this, as it's only an internal change and it's not worth updating a crap load of mods for nothing

**Comment by TheDoctorSoda** [comment]
Hmm fair enough. Do you know how many mods use this right now?

**Comment by modmuss50** [comment]
At least 3 of mine

**Pull request closed without merging**
